default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DATABASE_URL"] %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  host: localhost
  port: 5434
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  <% end %>

development:
  <<: *default
  database: ryanriegel_com_development

test:
  <<: *default
  database: ryanriegel_com_test

production:
  <<: *default
  database: ryanriegel_com_production
  username: ryanriegel
  password: <%= ENV["RYANRIEGEL_COM_DATABASE_PASSWORD"] %>
